[project]
name = "IEA-Wind-2200-22-ROWP"
version = "0.1.0"
description = "IEA Wind 2200-22-MW Reference Offshore Wind Plant"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = ">=3.9"
jsonschema = "*"
"ruamel.yaml" = "*"
xarray = "*"
netcdf4 = "*"
scipy = "*"
pyproj = "*"

[pypi-dependencies]
windIO = { path = "../windIO", editable = true }

[tasks]
validate = "python examples/validate.py"
convert-bathy = "python inputs/convert_bathymetry.py"
